src/main/java/com/uca/entity/UserEntity.java
package com.uca.entity;

import com.uca.core.PossessionCore;
import com.uca.core.TradeCore;

import java.time.LocalDate;
import java.util.ArrayList;

public class UserEntity {
    private String      firstName;
    private String      lastName;
    private int         id;
    private String      login;
    private String      pwdHash;
    private String      Email;
    private int         points;
    private LocalDate   dateConnexion;


    public UserEntity() {
        //Ignored !
    }

    public int getId() {
        return this.id;
    }

    public int getPoints() {
        return this.points;
    }

    public String getLogin() {
        return this.login;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public String getEmail() {
        return this.Email;
    }

    public LocalDate getDateConnexion() {
        return this.dateConnexion;
    }

    public String getPwdHash() {
        return this.pwdHash;
    }


    public void setId(int id) {
        this.id = id;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }


    public void setEmail(String E) {
        this.Email = E;
    }

    public void setDateConnexion(LocalDate date) {
        // voir plus tard comment creer l'objet date
        this.dateConnexion = date;
    }

    public void setPwdHash(String pwdHash) {
        this.pwdHash = pwdHash;
    }

    public void setPoints(int p) {
        this.points = p;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UserEntity that)) return false;

        if (!getPwdHash().equals(that.getPwdHash())) return false;
        return getLogin().equals(that.getLogin());
    }

    @Override

    public int hashCode() {
        int result = getPwdHash().hashCode();
        result = 31 * result + getEmail().hashCode();
        return result;
    }

    /**
     * A méthod to get the trades this user proposed, having the PENDING status
     *
     * @return
     */
    public ArrayList<TradeEntity> getProposedPendingTrades() {
        ArrayList<TradeEntity> tradeEntities = TradeCore.getTradesOfHavingStatus(this, TradeStatus.PENDING);
        for (TradeEntity tradeEntity : tradeEntities) {
            System.out.println(tradeEntity.getApplicantPossession().getOwner().getId() + "and " + this.getId());
        }
        tradeEntities.removeIf(tradeEntity -> tradeEntity.getApplicantPossession().getOwner().getId() != this.getId());
        return tradeEntities;
    }

    public ArrayList<TradeEntity> getReceivedPendingTrades() {
        ArrayList<TradeEntity> tradeEntities = TradeCore.getTradesOfHavingStatus(this, TradeStatus.PENDING);
        tradeEntities.removeIf((tradeEntity -> tradeEntity.getRecipientPossession().getOwner().getId() != this.getId()));
        return tradeEntities;
    }

    public ArrayList<PossessionEntity> getAvailableForTrade() {
        ArrayList<PossessionEntity> possessionEntities = new ArrayList<>();
        for (PossessionEntity possessionEntity : PossessionCore.activPossessionOf(this)) {
            if (!possessionEntity.isProposed())
                possessionEntities.add(possessionEntity);
        }
        return possessionEntities;

    }
}

src/main/resources/views/users/users.ftl
<#-- @ftlvariable name="users" type="java.util.Collection<com.uca.entity.UserEntity>" -->
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/style.css">

    <title>Liste des utilisateurs | PokeMy</title>
</head>
<body>
<header>
    <#include "../menu.ftl">
    <h1>Liste des utilisateurs</h1>
    <p> (Pour pouvoir tester toutes les fonctions du site, ne serait pas affichée comme ça sur un site publique</p>

</header>
<main>
    <table>
        <caption>Utilisateurs</caption>
        <thead>
        <tr>
            <th>Id</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Login</th>
            <th>Email</th>
            <th>Date de connexion</th>
        </tr>
        </thead>
        <tbody>

        <#list users as user>
        <tr class="row-link" onclick="window.location='/profile/${user.id}'">
            <td> ${user.id}</td>
            <td>${user.firstName}</td>
            <td>${user.lastName}</td>
            <td>${user.login}</td>
            <td>${user.email}</td>
            <td>${user.dateConnexion}</td>
        </tr>
    </#list>

        </tbody>
    </table>

</main>
</body>